name: custom_pc_new_model
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.2.0-42.2.beta <4.0.0'

dependencies:
  charset_converter: ^2.1.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  freezed_annotation:
  html: ^0.15.1
  http: ^0.13.5
  path: ^1.8.2
  riverpod_annotation:
  shared_preferences: ^2.2.2
  sqflite: ^2.2.8+4
  uuid: ^3.0.7

dev_dependencies:
  build_runner:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed:
  pedantic_mono: ^1.24.0+1
  riverpod_generator:
  riverpod_lint:
  test: ^1.24.9

flutter:
  uses-material-design: true